# Default profile
spring:
  profiles:
    active:
      - prod
#      - dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  profiles: prod
#  datasource:
#    url: jdbc:h2:./hoaxify-prod
#  h2:
#    console:
#      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hoaxify-prod
    username: root
    password: 1asd
    #   spring boot 2 this is required for all non in-memory db
    initialization-mode: always
hoaxify:
  upload-path: uploads-prod
---
spring:
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles: dev
  datasource:
    url: jdbc:h2:mem:hoaxify-dev
hoaxify:
  upload-path: uploads-dev
#  upload-path: uploads-dev
#datasource:
#  username: toma
#  password: toma
---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test
datasource:
  username: toma
  password: toma