# Default profile
spring:
  profiles:
    active:
#      - prod
      - dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./hoaxify-prod
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
hoaxify:
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:hoaxify-dev
hoaxify:
  upload-path: uploads-dev
datasource:
  username: toma
  password: toma
---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test
datasource:
  username: toma
  password: toma