
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  ### User for both db ###
  datasource:
    username: toma
    password: toma

hoaxify:
  upload-path: uploads-test
